# Generated by Django 4.0.4 on 2022-06-06 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('morning', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Detail',
            fields=[
                ('ingredient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ingredient_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField()),
                ('calory', models.FloatField(default=0)),
                ('carbohydrate', models.FloatField()),
                ('sugar', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('sat_fat', models.FloatField()),
                ('trans_fat', models.FloatField(default=0.0)),
                ('cholesterol', models.FloatField()),
                ('product_category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField()),
                ('soduim', models.FloatField()),
                ('product_image', models.ImageField(default='DEFAULT.jpg', upload_to='product_image/%Y/%m/%d')),
                ('ingredient', models.CharField(default='Nothing', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='MEAL_PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.ForeignKey(db_column='meal_id', on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='userinfo.daily_meal')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='userinfo.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favor_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('favor_category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_allergy', models.CharField(max_length=100)),
                ('is_category', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
