# Generated by Django 4.0.4 on 2022-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serving_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
