# Generated by Django 4.0.4 on 2022-05-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favor_category',
            name='user',
        ),
    ]
