# Generated by Django 4.0.4 on 2022-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_product_company_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soduim',
            field=models.IntegerField(default=0),
        ),
    ]
