# Generated by Django 4.0.4 on 2022-05-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_remove_allergy_user_remove_favor_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favor_category',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
