# Generated by Django 4.0.4 on 2022-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_product_soduim'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trans_fat',
            field=models.IntegerField(default=0),
        ),
    ]
