# Generated by Django 4.0.4 on 2022-06-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_alter_product_cooking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specific',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
