# Generated by Django 4.0.4 on 2022-06-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_favor_category_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Meal',
            fields=[
                ('meal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('morning', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Detail',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sat_fat', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('product_category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(default='DEFAULT.jpg', upload_to='product_image/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='allergy',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MEAL_PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.daily_meal')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.product')),
            ],
        ),
    ]
