# Generated by Django 4.0.4 on 2022-06-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_alter_product_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specific',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
