# Generated by Django 4.0.4 on 2022-06-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_alter_product_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='DEFAULT.jpg', null=True, upload_to='product_image/%Y/%m/%d'),
        ),
    ]
