# Generated by Django 4.0.4 on 2022-06-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_allergy_user_daily_meal_user_favor_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calory',
            field=models.IntegerField(default=0),
        ),
    ]
