# Generated by Django 4.0.4 on 2022-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_product_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='cholesterol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sat_fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='soduim',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='trans_fat',
            field=models.FloatField(default=0.0),
        ),
    ]
