# Generated by Django 4.0.4 on 2022-06-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='soduim',
            new_name='sodium',
        ),
    ]
