# Generated by Django 4.0.4 on 2022-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_alter_product_amount_alter_product_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calory',
            field=models.FloatField(default=0),
        ),
    ]
